### ISSUE TITLE
Questions on training Edge2Image and Sketch2Image

### ISSUE THREAD

**Issue by alex4727** [GaParmar/img2img-turbo#13]
Hi! I appreciate your great work.

I have question regarding training recipes of Sketch2Image and Edge2Image models. 

1. What was the reason to train Sketch2Image from resumed checkpoint of Edge2Image? (I also checked that lora_rank for unet is increased from 8 to 128. How were there weights of lora rank 128 initialized?)
2. Do you plan to release the full training script for both cases?

Thanks!

**Comment by GaParmar** [comment]
Hi, 

Thank you for your interest in this project! 
1. We resumed the sketch2image from the edge2image model because it serves as a good initialization, following ControlNet. 

2. We have added the paired training script [here](https://github.com/GaParmar/img2img-turbo/blob/main/docs/training_pix2pix_turbo.md). Training the edge model and the sketch model can be done with this script!
